### PR TITLE
add a function that will actually list all metrics

### PR DESCRIPTION
**Pull request by Bachmann1234**
I wrote this to help me with a script im playing with. If y'all like it I can polish it

### CODE REVIEW

**Comment by jderrett** [comment]
@drio thoughts on this usage?
```python
>>> api.list_all_metrics()
<generator object list_all_metrics at 0x108167c80>
>>> len(list(api.list_all_metrics()))
166
```

**Comment by drio** [comment]
I will take a look and get back to you.

**Comment by drio** [comment]
Ok, this looks great, big :+1: (thanks @Bachmann1234). 
At some point we may want  `list_metrics()` to become an alias of `list_all_metrics()`. 

@jderrett If you are also fine with this PR I will merge it (I'll also modify the README) and push a new version asap.

**Comment by jderrett** [comment]
:+1: thanks guys!

**Pull request merged**
