### PR TITLE
Add support for Spaces and Charts

### PR DESCRIPTION
**Pull request by earthican**

### CODE REVIEW

**Comment by earthican** [comment]
#112

**Comment by josephruscio** [comment]
Awesome! cc @jderrett @drio can we get some eyes on this in the near future?

**Comment by jderrett** [comment]
Yep, I'll take a look as soon as I can. Looks like there are some failing tests so not sure if you're still working some things @earthican? Thanks!!

**Comment by earthican** [comment]
@jderrett looks like builds are failing for python 3+ :crying_cat_face: 
I'll take a look some time later though it might be a while since I'm not very familiar with python 3

**Comment by jderrett** [comment]
@earthican no problem, I can take a look :)

**Comment by niklibrato** [comment]
@earthican thanks for this! As a contributor you should have a [Librato t-shirt](https://www.evernote.com/l/AAWOImFF2O9NaaDNSMM33gWXwtvasg1ZeL4) - would you like me to send you one?

**Comment by jderrett** [comment]
@earthican I'm going to finish this out in https://github.com/librato/python-librato/pull/114, thanks a ton!

**Comment by earthican** [comment]
@jderrett sounds great!
@niklibrato I'd love one! :smile_cat:

**Comment by soumendra** [comment]
Any updates on this one?

**Comment by drio** [comment]
> Any updates on this one?

@jderrett it is almost done (https://github.com/librato/python-librato/pull/114). Expect a release soon.

**Pull request closed without merging**
