### PR TITLE
Updated instructions on querying service ID

### PR DESCRIPTION
**Pull request by gmckeever**

### CODE REVIEW

**Comment by benarent** [comment]
Could we be more explicit about what a service is? Is it inbound / outbound?

**Comment by nextmat** [comment]
Agree. These are alert services, it would be nice if we could call them that in the lib for clarity. 

FWIW I know this PR is a README change, but seems like this would be worth making clear in both the documentation and in the code (by renaming / aliasing the existing access).

**Comment by gmckeever** [comment]
I can specify in the readme that services are outbound integrations.

ex.
```
View all services (outbound integrations) created by the user. The service ID is included in the response.
```

@nextmat what do you have in mind about renaming / aliasing in the code? rename the service method to outbound_integrations, build an `outbound_integration` alias which references `service`?

**Comment by gmckeever** [comment]
Readme updated to specify that services are outbound integrations, but just looking for a bit of feedback on how to clarifiy this within the code.

**Comment by drio** [comment]
> just looking for a bit of feedback on how to clarify this within the code.

That method is implemented [here](https://github.com/librato/python-librato/blob/master/librato/__init__.py#L424). You can rename it to make it more clear what it does. After that, make sure you change the [tests](https://github.com/librato/python-librato/blob/8c8cb8a2000afde71492c32373c6386c7c52c7eb/tests/test_alerts.py#L113) accordingly. To run the tests: `$ make tox`. I'll show you how to make a release once the PR is accepted.

**Comment by nextmat** [comment]
> That method is implemented here. You can rename it to make it more clear what it does. After that, make sure you change the tests accordingly. To run the tests: $ make tox. I'll show you how to make a release once the PR is accepted.

If this method is renamed will it be a breaking change that would require a major version bump?

**Comment by nextmat** [comment]
> If this method is renamed will it be a breaking change that would require a major version bump?

If so we should probably continue to support the existing name as an alias and mark it as deprecated in the code.

**Comment by drio** [comment]
> If so we should probably continue to support the existing name as an alias and mark it as deprecated in the code.

Good catch! Thanks Matt.

**Pull request merged**
